import Foundation

enum L10n {
    static func t(_ key: String, _ language: AppLanguage) -> String {
        table[language]?[key] ?? table[.english]?[key] ?? key
    }

    static func themeName(_ theme: HanziTheme, _ language: AppLanguage) -> String {
        t("theme.\(theme.rawValue)", language)
    }

    static func templateName(_ template: ArtworkTemplate, _ language: AppLanguage) -> String {
        t("template.\(template.rawValue)", language)
    }

    static func languageName(_ language: AppLanguage, current: AppLanguage) -> String {
        switch language {
        case .english:
            return t("language.english", current)
        case .simplifiedChinese:
            return t("language.chinese", current)
        case .japanese:
            return t("language.japanese", current)
        }
    }
}

private let table: [AppLanguage: [String: String]] = [
    .english: [
        "tab.today": "Today",
        "tab.practice": "Practice",
        "tab.artworks": "Art",
        "tab.library": "Library",
        "tab.settings": "Settings",
        "today.eyebrow": "Daily Hanzi",
        "today.title": "Practice one quiet stroke",
        "today.start": "Start Practice",
        "today.practiceAgain": "Practice Again",
        "today.favorite": "Favorite",
        "today.unfavorite": "Saved",
        "today.streak": "Day Streak",
        "today.practiced": "Practiced",
        "today.artworks": "Artworks",
        "today.continue": "Continue Practice",
        "today.completed": "Completed Today",
        "today.empty": "Save a practice session and it will appear here.",
        "detail.eyebrow": "Character Detail",
        "detail.title": "Understand, then write",
        "detail.radical": "Radical",
        "detail.strokes": "Strokes",
        "detail.theme": "Theme",
        "detail.story": "Culture Note",
        "detail.strokePreview": "Stroke Hints",
        "detail.generate": "Make Art",
        "practice.eyebrow": "Brush Practice",
        "practice.undo": "Undo",
        "practice.clear": "Clear",
        "practice.guides": "Guide",
        "practice.compare": "Compare",
        "practice.save": "Save Practice",
        "practice.disabled": "Draw first to save",
        "practice.saved": "Practice saved",
        "practice.progress": "Strokes drawn",
        "art.eyebrow": "Art Studio",
        "art.title": "Make a Hanzi card",
        "art.choose": "Choose Character",
        "art.signature": "Signature",
        "art.signaturePlaceholder": "Your name",
        "art.create": "Save Artwork",
        "art.share": "Share",
        "art.empty": "Create your first artwork from a favorite character.",
        "art.saved": "Artwork saved",
        "art.deleted": "Artwork deleted",
        "library.eyebrow": "Hanzi Library",
        "library.title": "Find a character to write",
        "library.search": "Search character, pinyin, or meaning",
        "library.favorites": "Favorites",
        "library.all": "All",
        "library.noResults": "No characters found.",
        "library.showAll": "Show all characters",
        "settings.eyebrow": "Settings",
        "settings.title": "Language and support",
        "settings.language": "App Language",
        "settings.languageHint": "Your choice is saved on this device.",
        "settings.systemHint": "If no language is selected, Hanzi Brush infers one from system or region and falls back to English.",
        "settings.privacy": "Privacy Policy",
        "settings.privacySubtitle": "View data practices",
        "settings.support": "Support",
        "settings.supportSubtitle": "Open help page",
        "settings.email": "Email Support",
        "settings.emailSubtitle": "Send us a message",
        "settings.data": "Local Data",
        "settings.clearData": "Clear local progress",
        "settings.clearConfirm": "Clear",
        "settings.version": "Version 1.0.0",
        "settings.paid": "Paid app, no account, no backend.",
        "settings.cleared": "Local data cleared",
        "common.cancel": "Cancel",
        "common.delete": "Delete",
        "common.done": "Done",
        "common.back": "Back",
        "common.open": "Open",
        "common.selected": "Selected",
        "common.free": "Included",
        "common.pro": "Full App",
        "theme.blessing": "Blessing",
        "theme.nature": "Nature",
        "theme.feeling": "Feeling",
        "theme.season": "Season",
        "theme.wisdom": "Wisdom",
        "template.ricePaper": "Rice Paper",
        "template.cinnabar": "Cinnabar",
        "template.jade": "Jade",
        "template.festival": "Festival",
        "language.english": "English",
        "language.chinese": "Simplified Chinese",
        "language.japanese": "Japanese"
    ],
    .simplifiedChinese: [
        "tab.today": "今日",
        "tab.practice": "练习",
        "tab.artworks": "作品",
        "tab.library": "字库",
        "tab.settings": "设置",
        "today.eyebrow": "今日一字",
        "today.title": "安静练一笔",
        "today.start": "开始临摹",
        "today.practiceAgain": "再次练习",
        "today.favorite": "收藏",
        "today.unfavorite": "已收藏",
        "today.streak": "连续天数",
        "today.practiced": "已练汉字",
        "today.artworks": "本地作品",
        "today.continue": "继续练习",
        "today.completed": "今日已完成",
        "today.empty": "保存一次练习后，这里会显示最近记录。",
        "detail.eyebrow": "汉字详情",
        "detail.title": "理解，再下笔",
        "detail.radical": "部首",
        "detail.strokes": "笔画",
        "detail.theme": "主题",
        "detail.story": "文化说明",
        "detail.strokePreview": "笔顺提示",
        "detail.generate": "生成作品",
        "practice.eyebrow": "临摹练习",
        "practice.undo": "撤销",
        "practice.clear": "清空",
        "practice.guides": "格线",
        "practice.compare": "对照",
        "practice.save": "保存练习",
        "practice.disabled": "先写一笔再保存",
        "practice.saved": "练习已保存",
        "practice.progress": "已写笔迹",
        "art.eyebrow": "作品工坊",
        "art.title": "做一张汉字卡片",
        "art.choose": "选择汉字",
        "art.signature": "署名",
        "art.signaturePlaceholder": "你的名字",
        "art.create": "保存作品",
        "art.share": "分享",
        "art.empty": "从一个喜欢的汉字开始，创建第一张作品。",
        "art.saved": "作品已保存",
        "art.deleted": "作品已删除",
        "library.eyebrow": "主题字库",
        "library.title": "找到想练的字",
        "library.search": "搜索汉字、拼音或英文含义",
        "library.favorites": "收藏",
        "library.all": "全部",
        "library.noResults": "没有找到匹配的汉字。",
        "library.showAll": "显示全部汉字",
        "settings.eyebrow": "设置",
        "settings.title": "语言与支持",
        "settings.language": "App 语言",
        "settings.languageHint": "你的选择会保存在本机。",
        "settings.systemHint": "没有选择语言时，App 会按系统或地区推断，兜底英文。",
        "settings.privacy": "隐私政策",
        "settings.privacySubtitle": "查看数据说明",
        "settings.support": "支持页面",
        "settings.supportSubtitle": "打开帮助页面",
        "settings.email": "邮件支持",
        "settings.emailSubtitle": "发送邮件给我们",
        "settings.data": "本地数据",
        "settings.clearData": "清除本地进度",
        "settings.clearConfirm": "清除",
        "settings.version": "版本 1.0.0",
        "settings.paid": "付费下载 App，无账号、无后端。",
        "settings.cleared": "本地数据已清除",
        "common.cancel": "取消",
        "common.delete": "删除",
        "common.done": "完成",
        "common.back": "返回",
        "common.open": "打开",
        "common.selected": "已选择",
        "common.free": "已包含",
        "common.pro": "完整版",
        "theme.blessing": "祝福",
        "theme.nature": "自然",
        "theme.feeling": "情感",
        "theme.season": "季节",
        "theme.wisdom": "智慧",
        "template.ricePaper": "宣纸",
        "template.cinnabar": "朱砂",
        "template.jade": "青玉",
        "template.festival": "节日",
        "language.english": "英语",
        "language.chinese": "简体中文",
        "language.japanese": "日语"
    ],
    .japanese: [
        "tab.today": "今日",
        "tab.practice": "練習",
        "tab.artworks": "作品",
        "tab.library": "字庫",
        "tab.settings": "設定",
        "today.eyebrow": "今日の漢字",
        "today.title": "静かに一筆を書く",
        "today.start": "練習を始める",
        "today.practiceAgain": "もう一度練習",
        "today.favorite": "保存",
        "today.unfavorite": "保存済み",
        "today.streak": "連続日数",
        "today.practiced": "練習済み",
        "today.artworks": "作品",
        "today.continue": "続けて練習",
        "today.completed": "今日完了",
        "today.empty": "練習を保存すると、ここに最近の記録が表示されます。",
        "detail.eyebrow": "漢字詳細",
        "detail.title": "理解してから書く",
        "detail.radical": "部首",
        "detail.strokes": "画数",
        "detail.theme": "テーマ",
        "detail.story": "文化メモ",
        "detail.strokePreview": "筆順ヒント",
        "detail.generate": "作品を作る",
        "practice.eyebrow": "なぞり練習",
        "practice.undo": "戻す",
        "practice.clear": "消す",
        "practice.guides": "ガイド",
        "practice.compare": "比較",
        "practice.save": "練習を保存",
        "practice.disabled": "まず一筆書いてください",
        "practice.saved": "練習を保存しました",
        "practice.progress": "書いた線",
        "art.eyebrow": "作品スタジオ",
        "art.title": "漢字カードを作る",
        "art.choose": "漢字を選ぶ",
        "art.signature": "署名",
        "art.signaturePlaceholder": "名前",
        "art.create": "作品を保存",
        "art.share": "共有",
        "art.empty": "好きな漢字から最初の作品を作りましょう。",
        "art.saved": "作品を保存しました",
        "art.deleted": "作品を削除しました",
        "library.eyebrow": "漢字ライブラリ",
        "library.title": "書きたい字を探す",
        "library.search": "漢字、ピンイン、意味を検索",
        "library.favorites": "保存",
        "library.all": "すべて",
        "library.noResults": "一致する漢字がありません。",
        "library.showAll": "すべて表示",
        "settings.eyebrow": "設定",
        "settings.title": "言語とサポート",
        "settings.language": "App の言語",
        "settings.languageHint": "選択はこの端末に保存されます。",
        "settings.systemHint": "未選択の場合、システムまたは地域から推定し、英語にフォールバックします。",
        "settings.privacy": "プライバシーポリシー",
        "settings.privacySubtitle": "データの取り扱いを確認",
        "settings.support": "サポート",
        "settings.supportSubtitle": "ヘルプページを開く",
        "settings.email": "メールサポート",
        "settings.emailSubtitle": "メールで問い合わせ",
        "settings.data": "ローカルデータ",
        "settings.clearData": "進捗を削除",
        "settings.clearConfirm": "削除",
        "settings.version": "バージョン 1.0.0",
        "settings.paid": "有料App、アカウントなし、バックエンドなし。",
        "settings.cleared": "ローカルデータを削除しました",
        "common.cancel": "キャンセル",
        "common.delete": "削除",
        "common.done": "完了",
        "common.back": "戻る",
        "common.open": "開く",
        "common.selected": "選択中",
        "common.free": "含まれる",
        "common.pro": "フル版",
        "theme.blessing": "祝福",
        "theme.nature": "自然",
        "theme.feeling": "感情",
        "theme.season": "季節",
        "theme.wisdom": "知恵",
        "template.ricePaper": "宣紙",
        "template.cinnabar": "朱砂",
        "template.jade": "青玉",
        "template.festival": "祭り",
        "language.english": "英語",
        "language.chinese": "簡体字中国語",
        "language.japanese": "日本語"
    ]
]
